- platform: mqtt
  name: "Shelly2 Power"
  state_topic: "shellies/shellyswitch-55B707/relay/power"
  unit_of_measurement: "Watts"    
- platform: mqtt
  name: "Shelly2 Energy"
  state_topic: "shellies/shellyswitch-55B707/relay/energy" 
  unit_of_measurement: "kWh" 
- platform: mqtt
  name: "Temperatur Stecker"
  stste_topic: "plug_2F5AE8/tele/SENSOR"
  value_template: 'v{{ value_json.AM2301.Temperature }}'
- platform: mqtt
  name: "Luftfeuchte Stecker"
  stste_topic: "plug_2F5AE8/tele/SENSOR"
  value_template: 'v{{ value_json.AM2301.Humidity }}'
  